config/routes.rb
Rails.application.routes.draw do
  root 'home#home'
  resources :rooms, except: %i[ show ] do
    resources :messages
  end
  get '/rooms/:room', to: 'rooms#show', as: 'show_room'
  get '/sessions/authorize', to: 'sessions#authorize', as: 'auth'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :user
  has_many :tokens, as: :tokenable
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :receiver, class_name: 'User'
  belongs_to :sender, class_name: 'User'
  belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :tokens, as: :tokenable
  has_many :user_rooms
  has_many :users, through: :user_rooms
  has_many :messages
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :tokenable, polymorphic: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tokens, as: :tokenable
  has_many :user_rooms
  has_many :rooms, through: :user_rooms
  has_many :sender_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :receiver_messages, class_name: 'Message', foreign_key: 'receiver_id'
  has_many :invitations
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_room, only: [:create]
  before_action :set_receiver, only: [:create]

  def create
    @message = current_user.sender_messages.build(message_params)
    if @message.save
      ActionCable.server.broadcast(
        "room_#{@room.room}",
        {
          body: @message.body
        }
      )
    end
  end

  private

  def set_room
    @room = Room.find(params[:room_id])
  end

  def set_receiver
    @receiver = User.last
  end

  def message_params
    params.require(:message)[:receiver_id] = @receiver.id
    params.require(:message)[:room_id] = @room.id
    params.require(:message).permit(:body, :receiver_id, :room_id)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @room = Room.find_by_room(params[:room])
    @message = Message.new
    @conversation = current_user.sender_messages.where(room_id: @room.id)
  end

  def new
    @room = Room.new
  end

  def create
    @user = User.find_or_create_by(user_params)
    unless @user.nil?
      session[:user_id] = @user.id
      @room = @user.rooms.build(room: SecureRandom.alphanumeric(15), uuid: SecureRandom.uuid)
    end
    respond_to do |format|
      if @room.save
        self.assing_room_to_user @room.id
        format.html { redirect_to show_room_path(room: @room.room) }
      else
        format.html { render :new, notice: 'An error has occured, try again', status: :unprocessable_entity }
      end
    end
  end

  def assing_room_to_user room_id
    room = Room.find(room_id)
    current_user.rooms << room
    EmailConfirmationJob.perform_async(current_user.id, room.id)
  end

  private

  def user_params
    params.require(:room).permit(:username, :email)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def authorize
    token =  params[:token]
    room = params[:room]
    decoded = TokenizeService.new({ token: token }).decode_token

    if user_exist?(decoded[0]['email']).nil?
      redirect_to '/401.html'
      return
    end

    redirect_to show_room_path(room), notice: "You confirmed your email successfully"
  end

  def user_exist? email
    User.find_by_email(email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/home/home.html.erb
<%= turbo_frame_tag "new_chat_room" do %>
  <%= link_to "New chat room", new_room_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <main class="container mx-auto py-28 px-5 flex relative h-screen w-full">
      <%= yield %>
    </main>
  </body>
</html>

app/views/rooms/new.html.erb
<%= turbo_frame_tag "new_chat_room" do %>
  <%= form_with(model: @room, data: { turbo: "false" }) do |f| %>
    <div>
      <%= f.label :username, "Username" %>
      <%= f.text_field :username, placeholder: "John Doe" %>
    </div>
    <div>
      <%= f.label :email, "Email" %>
      <%= f.text_field :email, placeholder: "email@example.com" %>
    </div>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/rooms/show.html.erb
<div id="<%= @room.room %>" class="container border-2 w-full h-full flex flex-col justify-end items-center" data-room="<%= @room.room %>">
  <div id="conversation" class="bg-[crimson] w-full">
    <% @conversation.each do |message| %>
      <% if message.sender_id == current_user.id %>
        <p><%= message.body %></p>
      <% else %>
        <p><%= message.body %></p>
      <% end %>
    <% end %>
  </div>
  <div class="w-full relative">
    <%= form_with(model: [@room, @message], class: "w-full flex justify-center items-center gap-3") do |f| %>
      <%= f.text_area :body, placeholder: "Message", class: "w-full border-slate-400" %>
      <%= f.submit "Send", class: "bg-green-400 px-5 py-2 rounded-full w-[50px] h-[50px]" %>
    <% end %>
  </div>
</div>

app/views/shared/_email_confirmation.html.erb
<p>An email confirmation was sent to <%= email %></p>